# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prog', '0003_monthjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adress',
            field=models.CharField(blank=True, default=b' ', max_length=256, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430 \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, default=b' ', max_length=256, verbose_name='\u041e\u0441\u0432\u0456\u0442\u0430'),
        ),
    ]
