# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prog', '0004_auto_20170611_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exp',
            field=models.CharField(blank=True, default=b' ', max_length=256, verbose_name='\u0414\u043e\u0441\u0432\u0456\u0434(\u0440\u043e\u043a\u0438)'),
        ),
    ]
