# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prog', '0005_employee_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Numb',
            field=models.CharField(blank=True, default=b' ', max_length=256, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d(\u043c\u043e\u0431.)'),
        ),
    ]
